

-- Buttons
buttons = {
    retry = {
        click_function = "retry",
        function_owner = self,
        label          = "Fix missing objects \n and click me \n to retry",
        position       = {0, 0, 2.6},
        scale          = {1.0,   1.0, 2.0 },
        rotation       = {0, 0, 0},
        width          = 1000,
        height         = 500,
        font_size      = 110,
        color          = hexToColor("#823030"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "Place missing objects and retry", 
    },
    retrieve = {
        click_function = "retrieve",
        function_owner = self,
        label          = "→ Explore a Site\nfrom the front.",
        position       = {-1.85, 0, -0.85},
        scale          = {1.0,   1.0,   2.0 },
        rotation       = {0, 0, 0},
        width          = 725,
        height         = 400,
        font_size      = 77,
        color          = hexToColor("#588087"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "Retrieve a Site and all objects there from the front of the Atlas Box", 
    },
    retrieveBack = {
        click_function = "retrieveBack",
        function_owner = self,
        label          = "↓ Revisit this site from the back.",
        position       = {-1.85, 0, 0.25},
        scale          = {1.0,   1.0,   2.0 },
        rotation       = {0, 0, 0},
        width          = 725,
        height         = 100,
        font_size      = 50,
        color          = hexToColor("#588087"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "Retrieve a Site and all objects there from the back of the Atlas Box", 
    },
    ruinSites = {
        click_function = "ruinSites",
        function_owner = self,
        label          = "Ruin and\n Unify Sites",
        position       = {1.85, 0, -0.85},
        scale          = {1.0,   1.0,   2.0 },
        rotation       = {0, 0, 0},
        width          = 725,
        height         = 400,
        font_size      = 77,
        color          = hexToColor("#588087"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "Ruin Unpreserved Sites from Right to Left", 
    },
    setup = {
        click_function = "chronicleSetup",
        function_owner = self,
        label          = "Setup Initial\nAtlas Box, Sites, \n& World Deck",
        position       = {0, 0, 2.6},
        scale          = {1.0,   1.0, 2.0 },
        rotation       = {0, 0, 0},
        width          = 1000,
        height         = 500,
        font_size      = 130,
        color          = hexToColor("#4a915d"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "Set Up the Atlas Box for a new Chronicle", 
    },
    spawnRelics = {
        click_function = "spawnRelics",
        function_owner = self,
        label          = "Retrieve Lost Relics",
        position       = {0, 0, 2.1},
        scale          = {1.0,   1.0, 2.0 },
        rotation       = {0, 0, 0},
        width          = 1050,
        height         = 250,
        font_size      = 80,
        font_color     = hexToColor("#e6bb4a"),
        color          = hexToColor("#8a363b"),
        tooltip        = "Retrieve 10 relics from the Atlas Box if you run out", 
    }
}