

-- Buttons
buttons = {
    retry = {
        click_function = "retry",
        function_owner = self,
        label          = "Fix missing objects \n and click me \nto retry",
        position       = {1.75, -0.99, 0},
        scale          = {2.2, 1.0, 2.2 },
        rotation       = {0, 270, 0},
        width          = 1000,
        height         = 500,
        font_size      = 110,
        color          = hexToColor("#823030"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "Place missing objects and retry", 
    },
    setup = {
        click_function = "chronicleSetup",
        function_owner = self,
        label          = "Setup Initial\nAtlas Box, Sites, \n& World Deck",
        position       = {1.75, -0.99, 0},
        scale          = {2.2, 1.0, 2.2 },
        rotation       = {0, 270, 0},
        width          = 1000,
        height         = 500,
        font_size      = 130,
        color          = hexToColor("#4a915d"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "Set Up the Atlas Box for a new Chronicle", 
    },
    speedLabel = {
        click_function = "nothing",
        function_owner = self,
        label          = "Speed",
        position       = {-0.65, 0.55, -2.38},
        scale          = {1, 1.0, 1 },
        rotation       = {90, 180, 0},
        width          = 0,
        height         = 0,
        font_size      = 130,
        color          = hexToColor("#4a915d"),
        font_color     = {1, 1, 1, 1},
    },
    speedDisplay = {
        click_function = "nothing",
        function_owner = self,
        label          = "30",
        position       = {-0.65, 0.00, -2.38},
        scale          = {1, 1.0, 1 },
        rotation       = {90, 180, 0},
        width          = 0,
        height         = 0,
        font_size      = 200,
        color          = hexToColor("#4a915d"),
        font_color     = {1, 1, 1, 1},
        tooltip        = "speedDisplay" 
    },
    speedUp = {
        click_function = "speedUp",
        function_owner = self,
        label          = "+",
        position       = {-1.15, 0.025, -2.38},
        scale          = {0.75, 1.0, 0.75},
        rotation       = {90, 180, 0},
        width          = 300,
        height         = 300,
        font_size      = 200,
        color          = hexToColor("#999999"),
        font_color     = {1, 1, 1, 1},
    },
    speedDown = {
        click_function = "speedDown",
        function_owner = self,
        label          = "-",
        position       = {-0.15, 0.025, -2.38},
        scale          = {0.75, 1.0, 0.75},
        rotation       = {90, 180, 0},
        width          = 300,
        height         = 300,
        font_size      = 200,
        color          = hexToColor("#999999"),
        font_color     = {1, 1, 1, 1},
    },
}