deckLookup = {
    [361] = "Hearth",
    [362] = "Arcane",
    [363] = "Beast",
    [364] = "Discord",
    [365] = "Order",
    [366] = "Nomad"     
}

edificeDeckLookup = {
    [392] = "Hearth",
    [390] = "Arcane",
    [393] = "Beast",
    [389] = "Discord",
    [391] = "Order",
    [394] = "Nomad"
}

cardIndex = {
    Arcane = {
        cards = {
            [0] = { name = "Alchemist",            id =   9 },
            [1] = { name = "Fire Talkers",         id =  31 },
            [2] = { name = "Magician's Code",      id =  32 },
            [3] = { name = "Spirit Snare",         id =  33 },
            [4] = { name = "Wizard School",        id =  34 },
            [5] = { name = "Dazzle",               id =  35 },
            [6] = { name = "Acting Troupe",        id =  36 },
            [7] = { name = "Taming Charm",         id =  37 },
            [8] = { name = "Inquisitor",           id =  38 },
            [9] = { name = "Secret Signal",        id =  55 },
            [10] = {name = "Augury",               id =  56 },
            [11] = {name = "Rusting Ray",          id =  57 },
            [12] = {name = "Quick Exit",           id =  58 },
            [13] = {name = "Billowing Fog",        id =  59 },
            [14] = {name = "Kindred Warriors",     id =  60 },
            [15] = {name = "Terror Spells",        id =  61 },
            [16] = {name = "Blood Pact",           id =  62 },
            [17] = {name = "Revelation",           id =  63 },
            [18] = {name = "Observatory",          id =  64 },
            [19] = {name = "Plague Engines",       id =  65 },
            [20] = {name = "Gleaming Armor",       id =  66 },
            [21] = {name = "Bewitch",              id =  67 },
            [22] = {name = "Jinx",                 id =  68 },
            [23] = {name = "Tutor",                id =  69 },
            [24] = {name = "Dream Thief",          id =  70 },
            [25] = {name = "Cracking Ground",      id =  71 },
            [26] = {name = "Sealing Ward",         id =  72 },
            [27] = {name = "Initiation Rite",      id =  73 },
            [28] = {name = "Vow of Silence",       id =  74 },
            [29] = {name = "Forgotten Vault",      id =  75 },
            [30] = {name = "Map Library",          id =  76 },
            [31] = {name = "Witch's Bargain",      id =  77 },
            [32] = {name = "Master of Disguise",   id =  78 },
            [33] = {name = "Golem Legions",        id = 199 },
            [34] = {name = "Council Arbiter",      id = 200 },
            [35] = {name = "Catacombs",            id = 201 },
            [36] = {name = "Ward of Silence",      id = 202 },
            [37] = {name = "Vow of Wisdom",        id = 203 },
            [38] = {name = "Arcane Brokers",       id = 204 },
            [39] = {name = "Disciples",            id = 205 },
            [40] = {name = "Arcane Armor",         id = 206 },
            [41] = {name = "Glamor",               id = 207 },
            [42] = {name = "Wizard's Conclave",    id = 208 },
        },
    },

    Beast = {
        cards = {
            [0] = { name = "Errand Boy",            id =  11 },
            [1] = { name = "Wolves",                id =  39 },
            [2] = { name = "Animal Playmates",      id =  40 },
            [3] = { name = "True Names",            id =  41 },
            [4] = { name = "The Old Oak",           id =  42 },
            [5] = { name = "Forest Paths",          id =  43 },
            [6] = { name = "Long-Lost Heir",        id =  44 },
            [7] = { name = "Rangers",               id =  45 },
            [8] = { name = "Roving Terror",         id =  46 },
            [9] = { name = "Nature Worship",        id = 175 },
            [10] = {name = "Birdsong",              id = 176 },
            [11] = {name = "Small Friends",         id = 177 },
            [12] = {name = "Grasping Vines",        id = 178 },
            [13] = {name = "Threatening Roar",      id = 179 },
            [14] = {name = "Fae Merchant",          id = 180 },
            [15] = {name = "Second Chance",         id = 181 },
            [16] = {name = "Pied Piper",            id = 182 },
            [17] = {name = "Mushrooms",             id = 183 },
            [18] = {name = "Insect Swarm",          id = 184 },
            [19] = {name = "Vow of Union",          id = 185 },
            [20] = {name = "Giant Python",          id = 186 },
            [21] = {name = "War Tortoise",          id = 187 },
            [22] = {name = "New Growth",            id = 188 },
            [23] = {name = "Wild Cry",              id = 189 },
            [24] = {name = "Animal Host",           id = 190 },
            [25] = {name = "Memory of Nature",      id = 191 },
            [26] = {name = "Marsh Spirit",          id = 192 },
            [27] = {name = "Vow of Poverty",        id = 193 },
            [28] = {name = "Forest Council",        id = 194 },
            [29] = {name = "Walled Garden",         id = 195 },
            [30] = {name = "Vow of Beastkin",       id = 196 },
            [31] = {name = "Bracken",               id = 197 },
            [32] = {name = "Wild Allies",           id = 198 },
            [33] = {name = "True Oath",             id = 209 },
            [34] = {name = "Bog",                   id = 210 },
            [35] = {name = "Whispering Leaves",     id = 211 },
            [36] = {name = "Bed of Roots",          id = 212 },
            [37] = {name = "Autumn Wind",           id = 213 },
            [38] = {name = "Shifting Fog",          id = 214 },
            [39] = {name = "Fae Battalion",         id = 215 },
            [40] = {name = "Hunger",                id = 216 },
            [41] = {name = "Signal Trees",          id = 217 },
            [42] = {name = "Forest Warden",         id = 218 },
        },
    },

    Discord = {
        cards = {
            [0] = { name = "Mercenaries",          id =  12 },
            [1] = { name = "A Small Favor",        id =  15 },
            [2] = { name = "Second Wind",          id =  16 },
            [3] = { name = "Sleight of Hand",      id =  17 },
            [4] = { name = "Key to the City",      id =  18 },
            [5] = { name = "Scryer",               id =  19 },
            [6] = { name = "Disgraced Captain",    id =  20 },
            [7] = { name = "Naysayers",            id =  21 },
            [8] = { name = "Book Burning",         id =  22 },
            [9] = { name = "Charlatan",            id =  79 },
            [10] = {name = "Assassin",             id =  80 },
            [11] = {name = "Downtrodden",          id =  81 },
            [12] = {name = "Blackmail",            id =  82 },
            [13] = {name = "Cracked Sage",         id =  83 },
            [14] = {name = "Dissent",              id =  84 },
            [15] = {name = "False Prophet",        id =  85 },
            [16] = {name = "Vow of Division",      id =  86 },
            [17] = {name = "Zealots",              id =  87 },
            [18] = {name = "Royal Ambitions",      id =  88 },
            [19] = {name = "Salt the Earth",       id =  89 },
            [20] = {name = "Beast Tamer",          id =  90 },
            [21] = {name = "Riots",                id =  91 },
            [22] = {name = "Silver Tongue",        id =  92 },
            [23] = {name = "Gambling Hall",        id =  93 },
            -- idx 24 (Boiling Lake) is a blanked-out Edifice placeholder card, no printed id
            [25] = {name = "Relic Thief",          id =  95 },
            [26] = {name = "Enchantress",          id =  96 },
            [27] = {name = "Insomnia",             id =  97 },
            [28] = {name = "Sneak Attack",         id =  98 },
            [29] = {name = "Gossip",               id =  99 },
            [30] = {name = "Bandit Chief",         id = 100 },
            [31] = {name = "Chaos Cult",           id = 101 },
            [32] = {name = "Defame",               id = 102 },
            [33] = {name = "Bandit Paymaster",     id = 219 },
            [34] = {name = "Reliquary Raid",       id = 220 },
            [35] = {name = "Tracker",              id = 221 },
            [36] = {name = "Banner Breakers",      id = 222 },
            [37] = {name = "Pledge to Discord",    id = 223 },
            [38] = {name = "Friendly Familiar",    id = 224 },
            [39] = {name = "Unstable Summon",      id = 225 },
            [40] = {name = "Bandit Prince",        id = 226 },
            [41] = {name = "Dark Enforcer",        id = 227 },
            [42] = {name = "Spoiled Supplies",     id = 228 },
        },
    },

    Hearth = {
        cards = {
            [0] = { name = "Tinker's Fair",        id =  13 },
            [1] = { name = "Wayside Inn",          id =  47 },
            [2] = { name = "Extra Provisions",     id =  48 },
            [3] = { name = "Memory of Home",       id =  49 },
            [4] = { name = "Welcoming Party",      id =  50 },
            [5] = { name = "Traveling Doctor",     id =  51 },
            [6] = { name = "Storyteller",          id =  52 },
            [7] = { name = "Armed Mob",            id =  53 },
            [8] = { name = "Tavern Songs",         id =  54 },
            [9] = { name = "Homesteaders",         id = 127 },
            [10] = {name = "Crop Rotation",        id = 128 },
            [11] = {name = "A Round of Ale",       id = 129 },
            [12] = {name = "Land Warden",          id = 130 },
            [13] = {name = "Charming Friend",      id = 131 },
            [14] = {name = "Village Constable",    id = 132 },
            [15] = {name = "Family Heirloom",      id = 133 },
            [16] = {name = "News from Afar",       id = 134 },
            [17] = {name = "Levelers",             id = 135 },
            [18] = {name = "Fabled Feast",         id = 136 },
            [19] = {name = "The Great Levy",       id = 137 },
            [20] = {name = "Hearts and Minds",     id = 138 },
            [21] = {name = "Relic Breaker",        id = 139 },
            [22] = {name = "Book Binders",         id = 140 },
            [23] = {name = "Ballot Box",           id = 141 },
            [24] = {name = "Saddle Makers",        id = 142 },
            [25] = {name = "Herald",               id = 143 },
            [26] = {name = "Rowdy Pub",            id = 144 },
            [27] = {name = "Vow of Peace",         id = 145 },
            [28] = {name = "Deed Writer",          id = 146 },
            [29] = {name = "Salad Days",           id = 147 },
            [30] = {name = "Marriage",             id = 148 },
            [31] = {name = "Hospital",             id = 149 },
            [32] = {name = "Awaited Return",       id = 150 },
            [33] = {name = "Old Songs",            id = 229 },
            [34] = {name = "Diplomat",             id = 230 },
            [35] = {name = "Village Idiot",        id = 231 },
            [36] = {name = "Spinning Bee",         id = 232 },
            [37] = {name = "Firebrand",            id = 233 },
            [38] = {name = "Watchdog",             id = 234 },
            [39] = {name = "Favored Son",          id = 235 },
            [40] = {name = "Town Meeting",         id = 236 },
            [41] = {name = "League Treaty",        id = 237 },
            [42] = {name = "Skilled Merchants",    id = 238 },
        },
    },

    Nomad = {
        cards = {
            [0] = { name = "Rain Boots",           id =  14 },
            [1] = { name = "Ancient Binding",      id =  23 },
            [2] = { name = "Horse Archers",        id =  24 },
            [3] = { name = "Warning Signals",      id =  25 },
            [4] = { name = "Elders",               id =  26 },
            [5] = { name = "The Gathering",        id =  27 },
            [6] = { name = "Faithful Friend",      id =  28 },
            [7] = { name = "Tents",                id =  29 },
            [8] = { name = "Great Herd",           id =  30 },
            [9] = { name = "Convoys",              id = 151 },
            [10] = {name = "Vow of Kinship",       id = 152 },
            [11] = {name = "Wild Mounts",          id = 153 },
            [12] = {name = "Lancers",              id = 154 },
            [13] = {name = "Mountain Giant",       id = 155 },
            [14] = {name = "Rival Khan",           id = 156 },
            [15] = {name = "Lost Tongue",          id = 157 },
            [16] = {name = "Special Envoy",        id = 158 },
            [17] = {name = "Resettle",             id = 159 },
            [18] = {name = "Oracle",               id = 160 },
            [19] = {name = "Pilgrimage",           id = 161 },
            [20] = {name = "Spell Breaker",        id = 162 },
            [21] = {name = "Mounted Patrol",       id = 163 },
            [22] = {name = "Great Crusade",        id = 164 },
            [23] = {name = "Ancient Bloodline",    id = 165 },
            [24] = {name = "Ancient Pact",         id = 166 },
            [25] = {name = "Storm Caller",         id = 167 },
            [26] = {name = "Family Wagon",         id = 168 },
            [27] = {name = "Way Station",          id = 169 },
            [28] = {name = "Twin Brother",         id = 170 },
            [29] = {name = "Hospitality",          id = 171 },
            [30] = {name = "A Fast Steed",         id = 172 },
            [31] = {name = "Relic Worship",        id = 173 },
            -- idx 32 (Sacred Ground) is a blanked-out Edifice placeholder card, no printed id
            [33] = {name = "Tribute Spoils",       id = 239 },
            [34] = {name = "Search Party",         id = 240 },
            [35] = {name = "Moving Market",        id = 241 },
            [36] = {name = "Traveling Negotiator", id = 242 },
            [37] = {name = "Pledge of Defense",    id = 243 },
            [38] = {name = "The Red Seer",         id = 244 },
            [39] = {name = "Royal Stables",        id = 245 },
            [40] = {name = "Call for Help",        id = 246 },
            [41] = {name = "Vow of Wandering",     id = 247 },
            [42] = {name = "Mounted Library",      id = 248 },
        },
    },

    Order = {
        cards = {
            [0] = { name = "Wrestlers",            id =   1 },
            [1] = { name = "Battle Honors",        id =   2 },
            [2] = { name = "Bear Traps",           id =   3 },
            [3] = { name = "Longbows",             id =   4 },
            [4] = { name = "Keep",                 id =   5 },
            [5] = { name = "Pressgangs",           id =   6 },
            [6] = { name = "Garrison",             id =   7 },
            [7] = { name = "Scouts",               id =   8 },
            [8] = { name = "Martial Culture",      id =  10 },
            [9] = { name = "Code of Honor",        id = 103 },
            [10] = {name = "Outriders",            id = 104 },
            [11] = {name = "Messenger",            id = 105 },
            [12] = {name = "Field Promotion",      id = 106 },
            [13] = {name = "Palanquin",            id = 107 },
            [14] = {name = "Shield Wall",          id = 108 },
            [15] = {name = "Military Parade",      id = 109 },
            -- idx 16 (Tome Guardians) is a blanked-out Edifice placeholder card, no printed id
            [17] = {name = "Tyrant",               id = 111 },
            [18] = {name = "Forced Labor",         id = 112 },
            [19] = {name = "Secret Police",        id = 113 },
            [20] = {name = "Specialist",           id = 114 },
            [21] = {name = "Captains",             id = 115 },
            [22] = {name = "Siege Engines",        id = 116 },
            [23] = {name = "Royal Tax",            id = 117 },
            [24] = {name = "Toll Roads",           id = 118 },
            [25] = {name = "Curfew",               id = 119 },
            [26] = {name = "Knights Errant",       id = 120 },
            [27] = {name = "Vow of Obedience",     id = 121 },
            [28] = {name = "Hunting Party",        id = 122 },
            [29] = {name = "Council Seat",         id = 123 },
            [30] = {name = "Encirclement",         id = 124 },
            [31] = {name = "Peace Envoy",          id = 125 },
            [32] = {name = "Relic Hunter",         id = 126 },
            [33] = {name = "Master at Arms",       id = 249 },
            [34] = {name = "Baron",                id = 250 },
            [35] = {name = "Honor Guard",          id = 251 },
            [36] = {name = "City Wall",            id = 252 },
            [37] = {name = "Fearsome General",     id = 253 },
            [38] = {name = "Careful Plans",        id = 254 },
            [39] = {name = "Garrison Armory",      id = 255 },
            [40] = {name = "Battle Axes",          id = 256 },
            [41] = {name = "Great Feast",          id = 257 },
            [42] = {name = "Quartermaster",        id = 258 },
        },
    },
}

relicIndex = {
    cards = {
        [0] = { name = "Sticky Fire",        id = 401 },
        [1] = { name = "Cursed Cauldron",    id = 402 },
        [2] = { name = "Brass Horse",        id = 403 },
        [3] = { name = "Truthful Harp",      id = 404 },
        [4] = { name = "Grand Mask",         id = 405 },
        [5] = { name = "Horned Mask",        id = 406 },
        [6] = { name = "Cup of Plenty",      id = 407 },
        [7] = { name = "Whistle",            id = 408 },
        [8] = { name = "Dowsing Sticks",     id = 409 },
        [9] = { name = "Cracked Horn",       id = 410 },
        [10] = {name = "Bandit Crown",       id = 411 },
        [11] = {name = "Ring of Devotion",   id = 412 },
        [12] = {name = "Skeleton Key",       id = 413 },
        [13] = {name = "Oracular Pig",       id = 414 },
        [14] = {name = "Circlet of Command", id = 415 },
        [15] = {name = "Ivory Eye",          id = 416 },
        [16] = {name = "Shifting Map",       id = 417 },
        [17] = {name = "Obsidian Cage",      id = 418 },
        [18] = {name = "Book of Records",    id = 419 },
        [19] = {name = "Dragonskin Drum",    id = 420 },
        [20] = {name = "Crystal Vial",       id = 421 },
        [21] = {name = "Ancient Writ",       id = 422 },
        [22] = {name = "Painted Trumpet",    id = 423 },
        [23] = {name = "Bone Dice",          id = 424 },
        [24] = {name = "Brass Army",         id = 425 },
        [25] = {name = "Imperial Seal",      id = 426 },
        [26] = {name = "Fearsome Shield",    id = 427 },
        [27] = {name = "Singing Mask",       id = 428 },
        [28] = {name = "Lost Tapestry",      id = 429 },
        [29] = {name = "Bandit Standard",    id = 430 },
        [30] = {name = "Silver Charm",       id = 431 },
        [31] = {name = "Amber Flame",        id = 432 },
        -- idx 32 is a blanked "Delete this card and redraw a new relic" placeholder
        [33] = {name = "Wine of Welcome",    id = 433 },
        [34] = {name = "Whispering Stone",   id = 434 },
        [35] = {name = "Black Sword",        id = 435 },
        [36] = {name = "Barbed Net",         id = 436 },
        -- idx 37 is a blanked "Delete this card and redraw a new relic" placeholder
        [38] = {name = "Bag of Siegeworks",  id = 437 },
        [39] = {name = "Secret Testament",   id = 438 },
        -- idx 40 is a blanked "Delete this card and redraw a new relic" placeholder
        [41] = {name = "Magic Carpet",       id = 439 },
        [42] = {name = "Yew Staff",          id = 440 },
        [43] = {name = "Spiteful Mirror",    id = 441 },
        [44] = {name = "Weeping Banner",     id = 442 },
        [45] = {name = "Sigil of the Eye",   id = 443 },
        [46] = {name = "Sigil of the Heart", id = 444 },
        [47] = {name = "Magic Waterskin",    id = 445 },
        [48] = {name = "Demon Tail",         id = 446 },
        [49] = {name = "Clay Rattle",        id = 447 }
    },
}

legacyIndex = {
    cards = {
        [0] = { name = "Iron Hand",                id = 501 },
        [1] = { name = "Chronicler",               id = 502 },
        [2] = { name = "Steadfast",                id = 503 },
        [3] = { name = "Peacemaker",               id = 504 },
        [4] = { name = "The Needle",               id = 505 },
        [5] = { name = "Circle of Swords",         id = 506 },
        [6] = { name = "Great Architect",          id = 507 },
        [7] = { name = "Ancestral Lands",          id = 508 },
        [8] = { name = "Scepter Bearer",           id = 509 },
        [9] = { name = "Royal Line",               id = 510 },
        [10] = {name = "Keeper of Order",          id = 511 },
        [11] = {name = "Golden Key",               id = 512 },
        [12] = {name = "World Crafter",            id = 513 },
        [13] = {name = "Matchmaker",               id = 514 },
        [14] = {name = "Revolutionary",            id = 515 },
        [15] = {name = "Populist",                 id = 516 },
        [16] = {name = "Rival",                    id = 517 },
        [17] = {name = "The Standard Bearer",      id = 518 },
        [18] = {name = "The Ear",                  id = 519 },
        [19] = {name = "Heirloom",                 id = 520 },
        [20] = {name = "High Priest",              id = 521 },
        [21] = {name = "Seer",                     id = 522 },
        [22] = {name = "Arbiter",                  id = 523 },
        [23] = {name = "The Bright Beacon",        id = 524 },
        [24] = {name = "Oaths of Loyalty",         id = 525 },
        [25] = {name = "Conspirator",              id = 526 },
        [26] = {name = "Light Fingers",            id = 527 },
        [27] = {name = "Secret Society",           id = 528 },
        [28] = {name = "Ruthless",                 id = 529 },
        [29] = {name = "Quest to Distant Lands",   id = 530 },
        [30] = {name = "Wealthy",                  id = 531 },
        [31] = {name = "Gatekeeper",               id = 532 },
        [32] = {name = "Beloved",                  id = 533 },
        [33] = {name = "The Mouth",                id = 534 },
        [34] = {name = "Reformer",                 id = 535 },
        [35] = {name = "Pathfinder",               id = 536 },
            },
}


edificeIndex = {
    Arcane = {
        cards = {
            [0] = { name = "Great Spire",           id = 611 },
            [1] = { name = "Great Clock",           id = 612 },
            [2] = { name = "Underground Library",   id = 613 },
            [3] = { name = "Stone Portal",          id = 614 },
            [4] = { name = "Marble Fountains",      id = 615 },
        },
    },
    Beast = {
        cards = {
            [0] = { name = "Hallowed Spring",       id = 626 },
            [1] = { name = "School of Vines",       id = 627 },
            [2] = { name = "Oaken Fortress",        id = 628 },
            [3] = { name = "Forbidden Forest",      id = 629 },
            [4] = { name = "Forest Horn",           id = 630 },
        },
    },
    Discord = {
        cards = {
            [0] = { name = "Festival District",     id = 621 },
            [1] = { name = "Proving Grounds",       id = 622 },
            [2] = { name = "Spiral Castle",         id = 623 },
            [3] = { name = "Boiling Lake",          id = 624 },
            [4] = { name = "Hidden Passages",       id = 625 },
        },
    },
    Hearth = {
        cards = {
            [0] = { name = "Hall of Debate",        id = 601 },
            [1] = { name = "Great Market",          id = 602 },
            [2] = { name = "Grand Canal",           id = 603 },
            [3] = { name = "Stone Baths",           id = 604 },
            [4] = { name = "Amber Doors",           id = 605 },
        },
    },
    Nomad = {
        cards = {
            [0] = { name = "Great Forge",           id = 606 },
            [1] = { name = "Wild Pastures",         id = 607 },
            [2] = { name = "Sacred Ground",         id = 608 },
            [3] = { name = "Giant's Path",          id = 609 },
            [4] = { name = "Temple of Ancestors",   id = 610 },
        },
    },
    Order = {
        cards = {
            [0] = { name = "Hall of Ministers",     id = 616 },
            [1] = { name = "Relic Patrols",         id = 617 },
            [2] = { name = "Tome Guardians",        id = 618 },
            [3] = { name = "The Tribunal",          id = 619 },
            [4] = { name = "Towering Rampart",      id = 620 },
        },
    },
}

siteIndex = {
    ["Ancient City"] = 0,
    ["Broken Peaks"] = 1,
    ["Buried Giant"] = 2,
        ["Sleeping Giant"] = 2,
        ["Gray Barrows"] = 2,
    ["Deep Woods"] = 3,
    ["Desolate Shore"] = 4,
    ["Dunes"] = 5,
    ["Fair Isle"] = 6,
    ["Golden Valley"] = 7,
    ["Great Slum"] = 8,
    ["Green Shore"] = 9,
    ["Headwaters"] = 10,
    ["Hidden Place"] = 11,
        ["Hidden City"] = 11,
    ["Mines"] = 12,
    ["Narrow Pass"] = 13,
    ["Painted Towers"] = 14,
    ["Riverbank"] = 15,
    ["Rocky Coast"] = 16,
    ["Salt Flats"] = 17,
    ["Shrouded Woods"] = 18,
    ["Solitary Pillar"] = 19,
    ["Standing Stones"] = 20,
        ["StandingStones"] = 20,
    ["Steppe"] = 21,
    ["Sunken Isles"] = 22,
    ["Tidal Marshes"] = 23,
}